default: &default
 adapter: postgresql
 encoding: unicode
 pool: 5
 username: <%= ENV['UY_DATABASE_USER'] %>
 password: <%= ENV['UY_DATABASE_PASSWORD'] %>
 host: localhost

development:
  <<: *default
  database: uy_database_development

test:
  <<: *default
  database: uy_database_test