default: &default
 adapter: postgresql
 encoding: utf8
 pool: 5
 username: <%= ENV['UY_DATABASE_USER'] %>
 password: <%= ENV['UY_DATABASE_PASSWORD'] %>
 host: localhost

development:
  <<: *default
  database: uy_database_development

test:
  <<: *default
  database: uy_database_test

production:
  adapter: postgresql
  encoding: utf8
  pool: 5
  url: <%= ENV["DATABASE_URL"]%>
